### ISSUE TITLE
Update serialize-javascript to version 2.1.1 or later

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/keybase-chat-widget#1]
https://github.com/mimblewimble/keybase-chat-widget/network/alert/src/web/yarn.lock/serialize-javascript/open

1 serialize-javascript vulnerability found in …/web/yarn.lock 2 days ago

## Not possible to fix automatically:
```
Dependabot cannot create a pull request as one or more other
dependencies require a version that is incompatible with this update.
```

## Remediation

Upgrade serialize-javascript to version 2.1.1 or later. For example:
```
serialize-javascript@^2.1.1:
  version "2.1.1"
```
Always verify the validity and compatibility of suggestions with your codebase.

## Details

GHSA-h9rv-jmmf-4pgx

moderate severity
Vulnerable versions: < 2.1.1
Patched version: 2.1.1
regular expressions Cross-Site Scripting (XSS) vulnerability

## Impact

Affected versions of this package are vulnerable to Cross-site Scripting (XSS). It does not properly mitigate against unsafe characters in serialized regular expressions.

This vulnerability is not affected on Node.js environment since Node.js's implementation of RegExp.prototype.toString() backslash-escapes all forward slashes in regular expressions.

If serialized data of regular expression objects are used in an environment other than Node.js, it is affected by this vulnerability.

## Patches

This was patched in v2.1.1.

**Comment by nijynot** [comment]
Will take a look at this today. :)
